language: go

go:
  - "1.11"

services:
  - docker

install:
  - echo "Hello World"

script:
  - make build_linux
  - make test
  - make build_images
  - make validate_client_proxy

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: master
