language: go

go:
  - "1.10"

services:
  - docker

install:
  - echo "Hello World"

script:
  - make build
  - make test
  - make build_image

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: master
