language: go

go:
  - "1.10"

install:
  - echo "Hello World"

script:
  - docker-compose -f docker-compose.yaml up -d consul
  - make build
  - make test
  - make build_image

deploy:
  - provider: script
    script: make upload_image
    on:
      branch: master
