version: '2.0'
services:
  client-proxy:
    build:
      context: ./client-proxy
      dockerfile: Dockerfile
    image: tsl8/nomad-client-proxy
  server-proxy:
    build:
      context: ./server-proxy
      dockerfile: Dockerfile
    image: tsl8/nomad-server-proxy
